### ISSUE TITLE
Select Credito-Contado

### ISSUE THREAD

**Issue by ferminarellano** [JDiGregorio/farosa#9]
No se asigno un valor por defecto al Select. Si el usuario no selecciona nada esto guarda un Null en la base de datos, el cliente dice que presentó problemas. El cliente solicita que se mantenga el toggle, que el problema gráfico que tenían ya no sale porque cambiaron de teléfonos.

**Comment by JDiGregorio** [comment]
Se realizó el cambio, se mantiene el toggle button al crear un pedido. #10
